/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sala.view;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import sala.controller.ObradaJelovnik;
import sala.controller.ObradaMladenci;
import sala.controller.ObradaOsoblje;
import sala.controller.ObradaSvadba;
import sala.model.Jelovnik;
import sala.model.Mladenci;
import sala.model.Osoblje;
import sala.model.Svadba;
import sala.pomocno.SalatestException;

/**
 *
 * @author Tomislav
 */
public class Svadbe extends javax.swing.JFrame {

    private final ObradaSvadba obradaEntitet;
    private final ObradaMladenci obradaMladenci;
    private final ObradaOsoblje obradaOsoblje;
    private static DefaultComboBoxModel<Jelovnik> modelJelovnik;
    private Svadba svadba;
    private DecimalFormat format;
    
    /**
     * Creates new form Svadbe
     */
    public Svadbe() {
        initComponents();
        obradaEntitet = new ObradaSvadba();
         obradaMladenci = new ObradaMladenci();
         obradaOsoblje = new ObradaOsoblje();
        
         
         DefaultComboBoxModel<Jelovnik> mj = new DefaultComboBoxModel<>();
         Jelovnik jm = new Jelovnik();
         jm.setSifra(0);
         jm.setNaziv("Odaberite Jelovnik");
         mj.addElement(jm);
         new ObradaJelovnik().getLista().forEach((j) -> {
         mj.addElement(j);
         });
        cmbJelovnik.setModel(mj);
         
         dpDatumSvadbe.setLocale(new Locale("hr", "HR"));
         dpDatumSvadbe.getSettings().setTranslationToday("Danas");
         dpDatumSvadbe.getSettings().setTranslationClear("Poništi");
         dpDatumSvadbe.getSettings().setFormatForDatesCommonEra("dd. MMMM yyyy.");
         dpDatumSvadbe.getSettings().setFormatForDatesBeforeCommonEra("dd. MMMM uuuu.");
         
         
         NumberFormat nf = NumberFormat.getInstance( new Locale("hr"));
        
        format = (DecimalFormat) nf;
        format.applyPattern("#,###.00");
        
         ucitajPodatke();
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntiteti = new javax.swing.JList<>();
        btnDodaj = new javax.swing.JButton();
        btnPromjeni = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCijena = new javax.swing.JTextField();
        dpDatumSvadbe = new com.github.lgooddatepicker.components.DatePicker();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBrojGostiju = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtStolovi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtKomentar = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMladenciUBazi = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMladenciUSvadbi = new javax.swing.JList<>();
        btnDodajMladenciUSvadbu = new javax.swing.JButton();
        txtUvjetMladenci = new javax.swing.JTextField();
        lmtMladenci = new javax.swing.JCheckBox();
        btnMladenciMakniSSvadbe = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstOsobljeUSvadbi = new javax.swing.JList<>();
        btnDodajOsobljeUSvadbu = new javax.swing.JButton();
        txtTraziOsobljeUBazi = new javax.swing.JTextField();
        lmtOsoblje = new javax.swing.JCheckBox();
        btnOsobljeMakniSSvadbe = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        lstOsobljeUBazi = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbJelovnik = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        btnOcistiPolja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstEntiteti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntitetiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntiteti);

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnPromjeni.setText("Promjeni");
        btnPromjeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromjeniActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obriši");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel4.setText("Cijena");

        jLabel5.setText("Datum");

        jLabel6.setText("Broj gostiju");

        jLabel7.setText("Stolovi");

        jLabel8.setText("Komentar");

        jScrollPane2.setViewportView(lstMladenciUBazi);

        jLabel9.setText("Korisnici u Bazi");

        jLabel10.setText("Korisnici u Svadbi");

        jScrollPane3.setViewportView(lstMladenciUSvadbi);

        btnDodajMladenciUSvadbu.setText(">>");
        btnDodajMladenciUSvadbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajMladenciUSvadbuActionPerformed(evt);
            }
        });

        txtUvjetMladenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUvjetMladenciActionPerformed(evt);
            }
        });

        lmtMladenci.setText("Limitiraj na 20");

        btnMladenciMakniSSvadbe.setText("<<");
        btnMladenciMakniSSvadbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMladenciMakniSSvadbeActionPerformed(evt);
            }
        });

        jScrollPane6.setViewportView(lstOsobljeUSvadbi);

        btnDodajOsobljeUSvadbu.setText(">>");
        btnDodajOsobljeUSvadbu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajOsobljeUSvadbuActionPerformed(evt);
            }
        });

        txtTraziOsobljeUBazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraziOsobljeUBaziActionPerformed(evt);
            }
        });

        lmtOsoblje.setText("Limitiraj na 20");

        btnOsobljeMakniSSvadbe.setText("<<");
        btnOsobljeMakniSSvadbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOsobljeMakniSSvadbeActionPerformed(evt);
            }
        });

        jScrollPane7.setViewportView(lstOsobljeUBazi);

        jLabel13.setText("Osoblje u Bazi");

        jLabel14.setText("Osoblje u Svadbi");

        jLabel1.setText("Jelovnik");

        jLabel2.setText("Naziv");

        btnOcistiPolja.setText("Očisti polja");
        btnOcistiPolja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcistiPoljaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnDodaj)
                                .addGap(18, 18, 18)
                                .addComponent(btnPromjeni)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnObrisi))
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(dpDatumSvadbe, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtKomentar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStolovi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBrojGostiju, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNaziv, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbJelovnik, javax.swing.GroupLayout.Alignment.LEADING, 0, 142, Short.MAX_VALUE)))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtUvjetMladenci, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lmtMladenci))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDodajMladenciUSvadbu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDodajOsobljeUSvadbu, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOsobljeMakniSSvadbe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTraziOsobljeUBazi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lmtOsoblje)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnOcistiPolja)))
                .addContainerGap(511, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(585, 585, 585)
                    .addComponent(btnMladenciMakniSSvadbe, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1138, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDodaj)
                                    .addComponent(btnPromjeni)
                                    .addComponent(btnObrisi)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(5, 5, 5)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtUvjetMladenci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lmtMladenci)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel2)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(134, 134, 134)
                                    .addComponent(btnDodajMladenciUSvadbu))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTraziOsobljeUBazi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lmtOsoblje))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(134, 134, 134)
                                    .addComponent(btnDodajOsobljeUSvadbu)
                                    .addGap(61, 61, 61)
                                    .addComponent(btnOsobljeMakniSSvadbe))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(cmbJelovnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtCijena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jLabel5)
                            .addGap(7, 7, 7)
                            .addComponent(dpDatumSvadbe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBrojGostiju, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtStolovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtKomentar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnOcistiPolja)
                .addGap(144, 144, 144))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(247, 247, 247)
                    .addComponent(btnMladenciMakniSSvadbe)
                    .addContainerGap(401, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstEntitetiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntitetiValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        ocistiPolja();
        
        svadba = lstEntiteti.getSelectedValue();
        
        if (svadba == null) {
            return;
        }
        
        
        txtNaziv.setText(svadba.getNaziv());
        txtBrojGostiju.setText(svadba.getBroj_gostiju());
        txtCijena.setText(format.format(svadba.getCijena()));
        txtKomentar.setText(svadba.getKomentar());
        txtStolovi.setText(svadba.getStolovi());
        
        if(svadba.getDatum() != null) {
            Date dt = new Date(svadba.getDatum().getTime());
            LocalDate d = dt.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            dpDatumSvadbe.setDate(d);
        }
        
        modelJelovnik = (DefaultComboBoxModel<Jelovnik>) cmbJelovnik.getModel();
        for (int i = 0; i < modelJelovnik.getSize(); i++) {
            if (modelJelovnik.getElementAt(i).getSifra() == svadba.getJelovnik().getSifra()) {
                cmbJelovnik.setSelectedIndex(i);
                break;
            }
        }
        
        ucitajOsoblje(svadba);
        ucitajMladence(svadba);
     
    }//GEN-LAST:event_lstEntitetiValueChanged

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
         Svadba s = new Svadba();
         s = preuzmiVrijednosti(s);
         spremi(s);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnPromjeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromjeniActionPerformed
        svadba = lstEntiteti.getSelectedValue();
        if (svadba == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite svadbu");
            return;
        }
        svadba = preuzmiVrijednosti(svadba);
        spremi(svadba);
    }//GEN-LAST:event_btnPromjeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
      svadba = lstEntiteti.getSelectedValue();
      if (svadba == null) {
          JOptionPane.showMessageDialog(null, "Prvo odaberite svadbu");
          return;
      }
        try {
            obradaEntitet.obrisi(svadba);
            ocistiPolja();
            ucitajPodatke();
        } catch (SalatestException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void txtUvjetMladenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUvjetMladenciActionPerformed
        ucitajMladence();
    }//GEN-LAST:event_txtUvjetMladenciActionPerformed

    private void btnDodajMladenciUSvadbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajMladenciUSvadbuActionPerformed
          if (svadba == null) {
          JOptionPane.showMessageDialog(null, "Prvo odaberite svadbu");
          return;
      }
      
      
      lstMladenciUBazi.getSelectedValuesList().forEach((p) -> {
      boolean postoji = false;
      for (int i = 0; i < lstMladenciUSvadbi.getModel().getSize(); i++) {
          if (p.getSifra() == lstMladenciUSvadbi.getModel().getElementAt(i).getSifra()) {
              postoji = true;
              break;
          }
      }
      if(!postoji) {
          svadba.getMladenci().add(p);
      }
      });
      
        ucitajMladence(svadba);
    }//GEN-LAST:event_btnDodajMladenciUSvadbuActionPerformed

    private void btnMladenciMakniSSvadbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMladenciMakniSSvadbeActionPerformed
        if (svadba == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite svadbu");
            return;
        }
        
        List<Integer> zaBrisanje = new ArrayList<>();
        lstMladenciUSvadbi.getSelectedValuesList().forEach((p) -> {
        zaBrisanje.add(p.getSifra());
        });
        
        for(int i=0; i<svadba.getMladenci().size();i++) {
            for (int b : zaBrisanje) {
                if (svadba.getMladenci().get(i).getSifra()==b) {
                    svadba.getMladenci().remove(i);
                    break;
                }
            }
        }
        
        
        ucitajMladence(svadba);
    }//GEN-LAST:event_btnMladenciMakniSSvadbeActionPerformed

    private void btnDodajOsobljeUSvadbuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajOsobljeUSvadbuActionPerformed
        
        if (svadba == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite svadbu");
            return;
        }
        
        lstOsobljeUBazi.getSelectedValuesList().forEach((o) -> {
        
            boolean postoji = false;
            for (int i = 0; i < lstOsobljeUSvadbi.getModel().getSize(); i++) {
                if (o.getSifra() == lstOsobljeUSvadbi.getModel().getElementAt(i).getSifra()) {
                    postoji = true;
                    break;
                }
            }
            if(!postoji) {
                svadba.getOsoblje().add(o);
            }
        });
        
        ucitajOsoblje(svadba);
    }//GEN-LAST:event_btnDodajOsobljeUSvadbuActionPerformed

    private void txtTraziOsobljeUBaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraziOsobljeUBaziActionPerformed
        ucitajOsoblje();
    }//GEN-LAST:event_txtTraziOsobljeUBaziActionPerformed

    private void btnOsobljeMakniSSvadbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOsobljeMakniSSvadbeActionPerformed
        if (svadba == null) {
            JOptionPane.showMessageDialog(null, "Prvo odaberite svadbu");
            return;
        }
        
        List<Integer> zaBrisanje = new ArrayList<>();
        lstOsobljeUSvadbi.getSelectedValuesList().forEach((p) -> {
        zaBrisanje.add(p.getSifra());
        });
        
        for(int i=0; i<svadba.getOsoblje().size();i++) {
            for (int b : zaBrisanje) {
                if (svadba.getOsoblje().get(i).getSifra()==b) {
                    svadba.getOsoblje().remove(i);
                    break;
                }
            }
        }
        
        
        ucitajOsoblje(svadba);
    }//GEN-LAST:event_btnOsobljeMakniSSvadbeActionPerformed

    private void btnOcistiPoljaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcistiPoljaActionPerformed
        ocistiPolja();
    }//GEN-LAST:event_btnOcistiPoljaActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnDodajMladenciUSvadbu;
    private javax.swing.JButton btnDodajOsobljeUSvadbu;
    private javax.swing.JButton btnMladenciMakniSSvadbe;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnOcistiPolja;
    private javax.swing.JButton btnOsobljeMakniSSvadbe;
    private javax.swing.JButton btnPromjeni;
    private javax.swing.JComboBox<Jelovnik> cmbJelovnik;
    private com.github.lgooddatepicker.components.DatePicker dpDatumSvadbe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JCheckBox lmtMladenci;
    private javax.swing.JCheckBox lmtOsoblje;
    private javax.swing.JList<Svadba> lstEntiteti;
    private javax.swing.JList<Mladenci> lstMladenciUBazi;
    private javax.swing.JList<Mladenci> lstMladenciUSvadbi;
    private javax.swing.JList<Osoblje> lstOsobljeUBazi;
    private javax.swing.JList<Osoblje> lstOsobljeUSvadbi;
    private javax.swing.JTextField txtBrojGostiju;
    private javax.swing.JTextField txtCijena;
    private javax.swing.JTextField txtKomentar;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtStolovi;
    private javax.swing.JTextField txtTraziOsobljeUBazi;
    private javax.swing.JTextField txtUvjetMladenci;
    // End of variables declaration//GEN-END:variables

    private void ucitajPodatke() {
         DefaultListModel<Svadba> m = new DefaultListModel<>();
         obradaEntitet.getLista().forEach((s) -> {
         m.addElement(s);
         });
         lstEntiteti.setModel(m);
    }
    private Svadba preuzmiVrijednosti (Svadba s) {
        s.setNaziv(txtNaziv.getText());
        s.setBroj_gostiju(txtBrojGostiju.getText());
        s.setKomentar(txtKomentar.getText());
        s.setStolovi(txtStolovi.getText());
        s.setJelovnik((Jelovnik) cmbJelovnik.getSelectedItem());
        try {
            Date date = Date.from(dpDatumSvadbe.getDate().atStartOfDay(ZoneId.systemDefault()).toInstant());
            s.setDatum(date);
        } catch (Exception e) {
            s.setDatum(null);
        }
        
         try {
            s.setCijena(
                    new BigDecimal(
                            format.parse(txtCijena.getText()).floatValue()
                    )
            );
        } catch (Exception e) {
           s.setCijena(BigDecimal.ZERO);
           txtCijena.setText("0");
        }
        return s;
    }
    private void ucitajOsoblje(Svadba s) {
       DefaultComboBoxModel<Osoblje> m = new DefaultComboBoxModel<>();
       
       s.getOsoblje().forEach((o) -> {
       m.addElement(o);
       });
       lstOsobljeUSvadbi.setModel(m);
    }
    
    private void spremi(Svadba s) {
        try {
            obradaEntitet.spremi(s);
            ocistiPolja();
            ucitajPodatke();
        } catch (SalatestException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    private void ucitajMladence(Svadba s) {
        DefaultListModel<Mladenci> m = new DefaultListModel<>();
        
        s.getMladenci().forEach((p) -> {
        m.addElement(p);
        });
        lstMladenciUSvadbi.setModel(m);
    }
    
    

    private void ocistiPolja() {
        txtNaziv.setText("");
        txtBrojGostiju.setText("");
        txtKomentar.setText("");
        txtStolovi.setText("");
        txtCijena.setText("");
        lstMladenciUSvadbi.setModel(new DefaultListModel<>());
        cmbJelovnik.setSelectedIndex(0);
        lstOsobljeUSvadbi.setModel(new DefaultListModel<>());
       
    }

    private void ucitajMladence() {
        if (lmtMladenci.isSelected()) {
            DefaultListModel<Mladenci> m = new DefaultListModel<>();
            for (Mladenci s : obradaMladenci.getLista(txtUvjetMladenci.getText().trim(), lmtMladenci.isSelected())) {
                m.addElement(s);
            }
            lstMladenciUBazi.setModel(m);
        }else {
            DefaultListModel<Mladenci> m = new DefaultListModel<>();
            Mladenci mm = new Mladenci();
            mm.setAdresa("Molim pričekati");
            m.addElement(mm);
            lstMladenciUBazi.setModel(m);
            Svadbe.DuzeUcitanjeMladenaca d = new Svadbe.DuzeUcitanjeMladenaca();
            d.start();
        }
    }

    private void ucitajOsoblje() {
        if(lmtOsoblje.isSelected()) {
            DefaultListModel<Osoblje> m = new DefaultListModel<>();
            for (Osoblje s : obradaOsoblje.getLista(txtTraziOsobljeUBazi.getText().trim(), lmtOsoblje.isSelected())) {
                m.addElement(s);
            }
             lstOsobljeUBazi.setModel(m);
        }else {
            DefaultListModel<Osoblje> m = new DefaultListModel<>();
            Osoblje o = new Osoblje();
            o.setIme("Molim");
            o.setPrezime("pričekati");
            m.addElement(o);
            lstOsobljeUBazi.setModel(m);
            Svadbe.DuzeUcitanjeOsoblje d = new Svadbe.DuzeUcitanjeOsoblje();
            d.start();
        }
    }

  private class DuzeUcitanjeOsoblje extends Thread {
      @Override
      public void run() {
          DefaultListModel<Osoblje> m = new DefaultListModel<>();
          for(Osoblje o : obradaOsoblje.getLista(txtTraziOsobljeUBazi.getText().trim(), lmtOsoblje.isSelected())) {
              m.addElement(o);
          }
          lstOsobljeUBazi.setModel(m);
      }
  }
    
    
    
    private class DuzeUcitanjeMladenaca extends Thread {
        @Override
        public void run () {
            DefaultListModel<Mladenci> m = new DefaultListModel<>();
            for(Mladenci s : obradaMladenci.getLista(txtUvjetMladenci.getText().trim(), lmtMladenci.isSelected())) {
                m.addElement(s);
            }
            lstMladenciUBazi.setModel(m);
        }
                
    }
}
